"""Type stubs for ``phyai_ext.radix_cache``."""

from __future__ import annotations

import enum
from typing import Any, Callable, Optional, Sequence

import tvm_ffi

MAX_TIERS: int

class Tier(enum.IntEnum):
    DEVICE = 0
    HOST = 1
    DISK = 2
    REMOTE = 3

class CacheEventKind(enum.IntEnum):
    INSERT = 0
    EVICT = 1
    PROMOTE_START = 2
    PROMOTE_DONE = 3
    PROMOTE_FAIL = 4
    DEMOTE_START = 5
    DEMOTE_DONE = 6
    DEMOTE_FAIL = 7
    SPLIT = 8

class CacheError(Exception): ...
class CacheCapacityError(CacheError, RuntimeError): ...
class CacheUsageError(CacheError, ValueError): ...
class CacheInvariantError(CacheError, RuntimeError): ...

class OwnedUnits(tvm_ffi.Object):
    def tier(self) -> Tier: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def ids(self) -> list[int]: ...
    def take_first(self, n: int) -> "OwnedUnits": ...
    def take_last(self, n: int) -> "OwnedUnits": ...
    def append(self, other: "OwnedUnits") -> None: ...

class NodeRef(tvm_ffi.Object):
    def node_handle(self) -> int: ...
    def tier(self) -> Tier: ...
    def valid(self) -> bool: ...

class CompositeNodeRef(tvm_ffi.Object):
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def valid(self) -> bool: ...
    def node_handle(self) -> int: ...

class MambaSlot(tvm_ffi.Object):
    def index(self) -> int: ...
    def valid(self) -> bool: ...

class CacheEvent(tvm_ffi.Object):
    kind: int
    tier_from: int
    tier_to: int
    handle: int
    atom_count: int
    unit_count: int
    ts_ns: int

    @property
    def kind_enum(self) -> CacheEventKind: ...
    @property
    def tier_from_enum(self) -> Tier: ...
    @property
    def tier_to_enum(self) -> Tier: ...

class MatchResult:
    last_node: list[int]
    matched_atoms: list[int]
    def __init__(self, last_node: list[int], matched_atoms: list[int]) -> None: ...

class HybridMatchResult:
    kv: MatchResult
    last_mamba_node: int
    mamba_branching_atoms: int

class PrefixCache:
    def __init__(
        self,
        atom_bytes: int,
        atoms_per_unit: int,
        device_total_units: int,
        host_total_units: int = ...,
        disk_total_units: int = ...,
        remote_total_units: int = ...,
        eviction_policy: str = ...,
        slru_threshold: int = ...,
        max_events_buffered: int = ...,
        device_max_pending_units: int = ...,
        host_max_pending_units: int = ...,
        disk_max_pending_units: int = ...,
        remote_max_pending_units: int = ...,
    ) -> None: ...
    @property
    def atom_bytes(self) -> int: ...
    @property
    def atoms_per_unit(self) -> int: ...
    @property
    def page_bytes(self) -> int: ...
    @property
    def policy_name(self) -> str: ...
    @property
    def slru_threshold(self) -> int: ...
    @property
    def impl(self) -> Any: ...
    def tier_enabled(self, tier: Tier) -> bool: ...
    def match(self, atoms: bytes | bytearray | memoryview) -> MatchResult: ...
    def collect_units(self, last_node: int, tier: Tier) -> Any: ...
    def insert(
        self, tier: Tier, atoms: bytes | bytearray | memoryview, units: OwnedUnits
    ) -> tuple[int, int, int]: ...
    def allocate(self, tier: Tier, n: int) -> OwnedUnits: ...
    def lock(self, tier: Tier, last_node: int) -> NodeRef: ...
    def lock_multi(self, last_node: int, tiers: Sequence[Tier]) -> CompositeNodeRef: ...
    def ensure_capacity(
        self, tier: Tier, n: int, promote_to: Optional[Tier] = ...
    ) -> None: ...
    def evict_by_predicate(
        self, tier: Tier, callback: Callable[[int, int, int, int, int], bool]
    ) -> int: ...
    def evict_by_named_predicate(self, tier: Tier, predicate: str, arg: int) -> int: ...
    def available(self, tier: Tier) -> int: ...
    def total(self, tier: Tier) -> int: ...
    def active(self, tier: Tier) -> int: ...
    def pending_units(self, tier: Tier) -> int: ...
    def max_pending_units(self, tier: Tier) -> int: ...
    def start_demote(self, node: int, src: Tier, dst: Tier) -> int: ...
    def start_promote(self, node: int, src: Tier, dst: Tier) -> int: ...
    def complete_op(self, handle: int, success: bool) -> None: ...
    def wait_op(self, handle: int, timeout_ms: int = ...) -> bool: ...
    def fail_all_inflight(self) -> int: ...
    def inflight_ops(self) -> list[int]: ...
    def add_evict_observer(self, callback: Callable[[int, int], None]) -> int: ...
    def remove_evict_observer(self, observer_id: int) -> bool: ...
    def take_events(self) -> list[CacheEvent]: ...
    @property
    def dropped_events(self) -> int: ...
    @property
    def current_step(self) -> int: ...
    def advance_step(self, n: int) -> None: ...
    def touch_step(self, node_handle: int) -> None: ...
    def node_path_hash(self, node_handle: int) -> int: ...

class HybridPrefixCache:
    def __init__(self, kv: PrefixCache, num_mamba_slots: int) -> None: ...
    @property
    def kv(self) -> PrefixCache: ...
    def match(self, atoms: bytes | bytearray | memoryview) -> HybridMatchResult: ...
    def allocate_mamba_slot(self) -> Optional[MambaSlot]: ...
    def attach_mamba(self, node_handle: int, slot: MambaSlot) -> None: ...
    def detach_mamba(self, node_handle: int) -> Optional[MambaSlot]: ...
    def find_last_mamba_node(self, from_handle: int) -> int: ...
    def ensure_mamba_capacity_by_evict(self, n: int) -> bool: ...
    @property
    def available_slots(self) -> int: ...
    @property
    def total_slots(self) -> int: ...
    @property
    def active_slots(self) -> int: ...

class StorageBackend:
    def __init__(self, impl: Any) -> None: ...
    @property
    def impl(self) -> Any: ...
    @property
    def name(self) -> str: ...
    @property
    def unit_bytes(self) -> int: ...
    def drain(self) -> None: ...
    def contains(self, key: int) -> bool: ...
    def entries(self) -> int: ...
    def write_sync(self, op_handle: int, key: int, ids: Sequence[int]) -> bool: ...
    def read_sync(self, op_handle: int, key: int, ids: Sequence[int]) -> bool: ...

def in_memory_storage_backend(unit_bytes: int) -> StorageBackend: ...
def file_storage_backend(path: str, unit_bytes: int) -> StorageBackend: ...
def xxh3_64(data: bytes | bytearray | memoryview) -> int: ...
def tree_node_depth_in_atoms(node_handle: int) -> int: ...
def tree_node_atom_count(node_handle: int) -> int: ...
def tree_node_hit_count(node_handle: int) -> int: ...
def tree_node_last_access_step(node_handle: int) -> int: ...
def tree_node_user_priority(node_handle: int) -> int: ...
def tree_node_set_user_priority(node_handle: int, priority: int) -> None: ...
def tree_node_has_mamba(node_handle: int) -> bool: ...
def tree_node_mamba_index(node_handle: int) -> int: ...
